services:
  postgres:
    container_name: app-nest-postgres-container
    image: postgres:16-alpine
    restart: unless-stopped
#    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: