version: "3.8"

services:
  #Postgres configuration
  postgres-db:
    container_name: postgres-container
    image: postgres:14-alpine
    restart: always
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data