export const entities = [
  {
    id: 1,
    type: "System",
    title: "System",
    editDate: new Date(2023, 4, 8),
    parentId: null,
    parentTitle: null,
  },
  {
    id: 2,
    type: "State",
    title: "New York",
    editDate: new Date(2023, 4, 8),
    parentId: null,
    parentTitle: null,
  },
  {
    id: 3,
    type: "State",
    title: "New Jersey",
    editDate: new Date(2023, 4, 8),
    parentId: null,
    parentTitle: null,
  },
  {
    id: 4,
    type: "District",
    title: "Brooklyn",
    editDate: new Date(2023, 4, 8),
    parentId: 2,
    parentTitle: "New York",
  },
  {
    id: 5,
    type: "District",
    title: "Manhattan",
    editDate: new Date(2023, 4, 8),
    parentId: 2,
    parentTitle: "New York",
  },
  {
    id: 6,
    type: "District",
    title: "Jersey City",
    editDate: new Date(2023, 4, 8),
    parentId: 3,
    parentTitle: "New Jersey",
  },
  {
    id: 7,
    type: "School",
    title: "6th Street Academy",
    editDate: new Date(2023, 4, 8),
    parentId: 5,
    parentTitle: "Manhattan",
  },
  {
    id: 8,
    type: "School",
    title: "#453",
    editDate: new Date(2023, 4, 8),
    parentId: 6,
    parentTitle: "Jersey City",
  },
  {
    id: 9,
    type: "Cohort",
    title: "Math Teachers",
    editDate: new Date(2023, 4, 8),
    parentId: null,
    parentTitle: null,
  },
  {
    id: 10,
    type: "Cohort",
    title: "English teachers",
    editDate: new Date(2023, 4, 8),
    parentId: null,
    parentTitle: null,
  },
  {
    id: 11,
    type: "System",
    title: "System",
    editDate: new Date(2023, 4, 8),
    parentId: null,
    parentTitle: null,
  },
  {
    id: 12,
    type: "State",
    title: "New York",
    editDate: new Date(2023, 4, 8),
    parentId: null,
    parentTitle: null,
  },
  {
    id: 13,
    type: "State",
    title: "New Jersey",
    editDate: new Date(2023, 4, 8),
    parentId: null,
    parentTitle: null,
  },
  {
    id: 14,
    type: "District",
    title: "Brooklyn",
    editDate: new Date(2023, 4, 8),
    parentId: 2,
    parentTitle: "New York",
  },
  {
    id: 15,
    type: "District",
    title: "Manhattan",
    editDate: new Date(2023, 4, 8),
    parentId: 2,
    parentTitle: "New York",
  },
  {
    id: 16,
    type: "District",
    title: "Jersey City",
    editDate: new Date(2023, 4, 8),
    parentId: 3,
    parentTitle: "New Jersey",
  },
  {
    id: 17,
    type: "School",
    title: "6th Street Academy",
    editDate: new Date(2023, 4, 8),
    parentId: 5,
    parentTitle: "Manhattan",
  },
  {
    id: 18,
    type: "School",
    title: "#453",
    editDate: new Date(2023, 4, 8),
    parentId: 6,
    parentTitle: "Jersey City",
  },
  {
    id: 19,
    type: "Cohort",
    title: "Math Teachers",
    editDate: new Date(2023, 4, 8),
    parentId: null,
    parentTitle: null,
  },
  {
    id: 20,
    type: "Cohort",
    title: "English teachers",
    editDate: new Date(2023, 4, 8),
    parentId: null,
    parentTitle: null,
  },
];

export const useAgenciesMockAPI = (): any => {
  return {
    entities,
    loading: false,
  };
};
